services:
  - type: web
    name: backend_contact
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend_contact.wsgi:application"
    envVars:
      - fromDotEnv: true
